#!/bin/bash
#

DATE="$(date)"
USER="$(whoami)"
BRANCH="$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')"
let POSITION="$(cat expat.log | wc -l) + 1"

echo $POSITION == $DATE == $BRANCH == $USER
